name: sym
description: Chess Bot
version: 1.0.0
project_author: Yunus Karaaslan
project_author_email: karaaslan.21@hotmail.com
project_author_phone: '+905319823347'

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
